# ==========================================
# CI/CD Pipeline
# GitHub → Docker → ACR → AKS
# With Azure DevOps Environment
# ==========================================

trigger:
- main


# ==========================================
# VARIABLES
# ==========================================

variables:

  # Docker Registry Service Connection
  dockerRegistryServiceConnection: '8072af9b-e881-4d56-9d7e-3b46abcb6e8b'

  # Azure Resource Manager Service Connection
  azureServiceConnection: 'azure-service-connection'


  # Azure Resource Group
  resourceGroup: 'rg-devops-project'


  # AKS Cluster Name
  aksCluster: 'aks-devops-project'


  # ACR Image Repository Name
  imageRepository: 'pankajkumardevdevopsrealtimeproject'


  # Azure Container Registry
  containerRegistry: 'pankajacr12345.azurecr.io'


  # Dockerfile Path
  dockerfilePath: '$(Build.SourcesDirectory)/BankingApp/Dockerfile'


  # Docker Image Tag
  tag: '$(Build.BuildId)'


  # Build Agent
  vmImageName: 'ubuntu-latest'


# ==========================================
# STAGES
# ==========================================

stages:


# ==========================================
# STAGE 1
# BUILD AND PUSH IMAGE TO ACR
# ==========================================

- stage: Build

  displayName: 'Build and Push to ACR'

  jobs:


  # ------------------------------------------
  # JOB: BUILD DOCKER IMAGE
  # ------------------------------------------

  - job: BuildDockerImage

    displayName: 'Build Docker Image'

    pool:

      vmImage: $(vmImageName)


    steps:


    # ------------------------------------------
    # Checkout GitHub Repository
    # ------------------------------------------

    - checkout: self

      displayName: 'Checkout Source Code'


    # ------------------------------------------
    # Build and Push Docker Image
    # ------------------------------------------

    - task: Docker@2

      displayName: 'Build and Push Docker Image to ACR'

      inputs:

        command: buildAndPush

        repository: $(imageRepository)

        dockerfile: $(dockerfilePath)

        containerRegistry: $(dockerRegistryServiceConnection)

        tags: |

          $(tag)


# ==========================================
# STAGE 2
# DEPLOY APPLICATION TO AKS
# ==========================================

- stage: Deploy

  displayName: 'Deploy to AKS'

  dependsOn: Build


  jobs:


  # ==========================================
  # DEPLOYMENT JOB
  # ==========================================

  - deployment: DeployToDevelopment

    displayName: 'Deploy Banking Application'


    # ------------------------------------------
    # AZURE DEVOPS ENVIRONMENT
    # ------------------------------------------

    environment: 'Development'


    # ------------------------------------------
    # AGENT
    # ------------------------------------------

    pool:

      vmImage: $(vmImageName)


    # ------------------------------------------
    # DEPLOYMENT STRATEGY
    # ------------------------------------------

    strategy:

      runOnce:


        deploy:


          steps:


          # ====================================
          # IMPORTANT
          # CHECKOUT REPOSITORY
          # ====================================

          - checkout: self

            displayName: 'Checkout Repository'


          # ====================================
          # DEBUG - CHECK FILES
          # ====================================

          - script: |

              echo "Current Directory:"
              pwd

              echo "=========================="

              echo "Repository Files:"
              ls -R $(Build.SourcesDirectory)

            displayName: 'Check Repository Files'


          # ====================================
          # DEPLOY TO AKS
          # ====================================

          - task: KubernetesManifest@1

            displayName: 'Deploy to AKS'

            inputs:

              action: deploy


              # Azure Connection Type
              connectionType: azureResourceManager


              # Azure Service Connection
              azureSubscriptionConnection: $(azureServiceConnection)


              # Resource Group
              azureResourceGroup: $(resourceGroup)


              # AKS Cluster
              kubernetesCluster: $(aksCluster)


              # Kubernetes YAML Files
              manifests: |

                $(Build.SourcesDirectory)/k8s/deployment.yaml

                $(Build.SourcesDirectory)/k8s/service.yaml


              # Replace Image in deployment.yaml
              containers: |

                $(containerRegistry)/$(imageRepository):$(tag)